db.url=jdbc:mysql://localhost:3306/real_estate_agent_finder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo
DB_URL=jdbc:mysql://localhost:3306/real_estate_agent_finder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo
db.user=root
DB_USER=root
db.password=root123
DB_PASSWORD=root123
